import type { ComponentProps } from "react";
import * as LucideIcons from "lucide-react";

export type IconName = keyof typeof LucideIcons;

export const tools = [
  // Diagnostic & AI Tools
  {
    name: "Symptom Checker",
    description: "Get a preliminary diagnosis based on symptoms using our advanced AI.",
    href: "/tools/symptom-checker",
    icon: "BrainCircuit" as IconName,
    category: "Diagnostic & AI Tools",
  },
  {
    name: "AI Diagnosis Assistant",
    description: "AI-powered assistant for preliminary diagnosis.",
    href: "/tools/ai-diagnosis-assistant",
    icon: "Bot" as IconName,
    category: "Diagnostic & AI Tools",
  },
  {
    name: "Radiology Toolkit",
    description: "A hub for X-Ray, Ultrasound, CT, and MRI analysis tools.",
    href: "/tools/radiology-toolkit",
    icon: "Radio" as IconName,
    category: "Diagnostic & AI Tools",
  },
  {
    name: "Skin Lesion Classifier",
    description: "AI-based analysis of skin lesion images.",
    href: "/tools/skin-lesion-classifier",
    icon: "Scan" as IconName,
    category: "Diagnostic & AI Tools",
  },
  {
    name: "Differential Diagnosis Generator",
    description: "Generate potential diagnoses from clinical findings.",
    href: "/tools/ddx-generator",
    icon: "Share2" as IconName,
    category: "Diagnostic & AI Tools",
  },
  {
    name: "Snellen Vision Test",
    description: "Simulate a Snellen chart for vision testing.",
    href: "/tools/snellen-test",
    icon: "Eye" as IconName,
    category: "Screening Tools",
  },
  {
    name: "Color Blindness Test",
    description: "Test for color vision deficiency using Ishihara plates.",
    href: "/tools/color-blind-test",
    icon: "Palette" as IconName,
    category: "Screening Tools",
  },
  {
    name: "Orthopedic ROM Analyzer",
    description: "Analyze range of motion from images or video.",
    href: "/tools/rom-analyzer",
    icon: "Move" as IconName,
    category: "Diagnostic & AI Tools",
  },
  // Cardiology
  {
    name: "Cardiology Toolkit",
    description: "A hub for ECG, murmurs, BP, and MI tools.",
    href: "/tools/cardiology-toolkit",
    icon: "HeartPulse" as IconName,
    category: "Specialty Toolkits",
  },
  {
    name: "Neurology Toolkit",
    description: "Tools for neurological assessment, including stroke scales and seizure logs.",
    href: "/tools/neurology-toolkit",
    icon: "Brain" as IconName,
    category: "Specialty Toolkits",
  },
  {
    name: "Fertility360",
    description: "A suite of tools for fertility and reproductive health.",
    href: "/tools/fertility-360",
    icon: "HeartHandshake" as IconName,
    category: "Specialty Toolkits",
  },
  // Cognitive & Neuro Tools
  {
    name: "Mini Mental State Exam (MMSE)",
    description: "Score and visually analyze the MMSE for cognitive function.",
    href: "/tools/mmse-scorer",
    icon: "BrainCircuit" as IconName,
    category: "Calculators & Scores",
  },
  // Pharmacology Tools
  {
    name: "Pharmacy",
    description: "A comprehensive database of medications with detailed information.",
    href: "/tools/pharmacy",
    icon: "Pill" as IconName,
    category: "Pharmacology Tools",
  },
  {
    name: "Pill Identifier",
    description: "Identify pills using AI with an image and text description.",
    href: "/tools/pill-identifier",
    icon: "Camera" as IconName,
    category: "Pharmacology Tools",
  },
  {
    name: "Drug Interaction Checker",
    description: "Check for potential interactions between different drugs.",
    href: "/tools/drug-interaction-checker",
    icon: "AlertTriangle" as IconName,
    category: "Pharmacology Tools",
  },
  {
    name: "Antibiotic Guide",
    description: "A guide to antibiotics based on medical conditions.",
    href: "/tools/antibiotic-guide",
    icon: "Book" as IconName,
    category: "Pharmacology Tools",
  },
   {
    name: "Dosage Calculator",
    description: "Calculate medication dosages for adults and pediatrics.",
    href: "/tools/dosage-calculator",
    icon: "Calculator" as IconName,
    category: "Calculators & Scores",
  },
   {
    name: "IV Drip Rate Calculator",
    description: "Calculate the drip rate for intravenous infusions.",
    href: "/tools/iv-drip-rate-calculator",
    icon: "Droplets" as IconName,
    category: "Calculators & Scores",
  },
  {
    name: "Prescription Writer",
    description: "Generate formatted, printable prescriptions.",
    href: "/tools/prescription-writer",
    icon: "FilePen" as IconName,
    category: "Clinical & Educational Tools",
  },
  {
    name: "Safe in Pregnancy? Checker",
    description: "Check medication safety during pregnancy and lactation.",
    href: "/tools/pregnancy-safety",
    icon: "Baby" as IconName,
    category: "Pharmacology Tools",
  },
  {
    name: "Contraindication Finder",
    description: "Find contraindications for specific drugs and conditions.",
    href: "/tools/contraindication-finder",
    icon: "ShieldBan" as IconName,
    category: "Pharmacology Tools",
  },
  // Lab Tools
  {
    name: "Lab Test Ranges",
    description: "Normal lab value ranges by age and gender.",
    href: "/tools/lab-test-ranges",
    icon: "NotebookText" as IconName,
    category: "Lab Tools",
  },
  {
    name: "Lab Interpretation Assistant",
    description: "AI-powered interpretation for CBC, LFTs, and KFTs.",
    href: "/tools/lab-interpretation-assistant",
    icon: "Beaker" as IconName,
    category: "Lab Tools",
  },
  {
    name: "Lab Report Analyzer",
    description: "Upload and analyze full lab reports for patterns with AI.",
    href: "/tools/lab-report-analyzer",
    icon: "TestTubeDiagonal" as IconName,
    category: "Lab Tools",
  },
  {
    name: "Urine Report Analyzer",
    description: "Analyze and interpret urinalysis reports.",
    href: "/tools/urine-analyzer",
    icon: "FlaskConical" as IconName,
    category: "Lab Tools",
  },
  // Calculators & Scores
  {
    name: "BMI Calculator",
    description: "Calculate Body Mass Index.",
    href: "/tools/bmi-calculator",
    icon: "User" as IconName,
    category: "Calculators & Scores",
  },
  {
    name: "BMR Calculator",
    description: "Calculate Basal Metabolic Rate.",
    href: "/tools/bmr-calculator",
    icon: "Flame" as IconName,
    category: "Calculators & Scores",
  },
  {
    name: "Creatinine Clearance",
    description: "Estimate kidney function via creatinine clearance.",
    href: "/tools/creatinine-clearance",
    icon: "Filter" as IconName,
    category: "Calculators & Scores",
  },
  // Clinical & Educational Tools
  {
    name: "SOAP Note Generator",
    description: "Generate structured SOAP notes from patient data.",
    href: "/tools/soap-note-generator",
    icon: "FileSignature" as IconName,
    category: "Clinical & Educational Tools",
  },
  {
    name: "Case Summary Generator",
    description: "Generate structured case summaries from clinical notes.",
    href: "/tools/case-summary",
    icon: "FileText" as IconName,
    category: "Clinical & Educational Tools",
  },
   {
    name: "Disease Summary Builder",
    description: "Get AI-powered, high-yield summaries of medical conditions.",
    href: "/tools/disease-summary-builder",
    icon: "BookOpenCheck" as IconName,
    category: "Clinical & Educational Tools",
  },
   {
    name: "Anatomy Atlas",
    description: "A visual guide to human anatomy systems.",
    href: "/tools/anatomy-atlas",
    icon: "Body" as IconName,
    category: "Clinical & Educational Tools",
  },
  {
    name: "OSCE Timer & Checklist",
    description: "Customizable timers and checklists for OSCE practice.",
    href: "/tools/osce-timer",
    icon: "Timer" as IconName,
    category: "Clinical & Educational Tools",
  },
  {
    name: "Mnemonic Generator",
    description: "Generate memorable mnemonics for medical topics.",
    href: "/tools/mnemonic-generator",
    icon: "Lightbulb" as IconName,
    category: "Clinical & Educational Tools",
  },
   {
    name: "Flashcards & Quizzes",
    description: "Test your knowledge with quizzes on various medical subjects.",
    href: "/tools/flashcards",
    icon: "Layers" as IconName,
    category: "Clinical & Educational Tools",
  },
  {
    name: "Clinical Case Simulations",
    description: "Scenario-based MCQs to test your clinical reasoning.",
    href: "/tools/case-simulations",
    icon: "ClipboardCheck" as IconName,
    category: "Clinical & Educational Tools",
  },
  // Patient-Facing Tools
  {
    name: "PHQ-9 Depression Test",
    description: "Screen for and monitor depression severity.",
    href: "/tools/phq9-test",
    icon: "SmilePlus" as IconName,
    category: "Screening Tools",
  },
  {
    name: "GAD-7 Anxiety Test",
    description: "Screen for and measure the severity of generalized anxiety disorder.",
    href: "/tools/gad7-test",
    icon: "Brain" as IconName,
    category: "Screening Tools",
  },
  {
    name: "Health Diary",
    description: "Track your symptoms, mood, and daily activities.",
    href: "/tools/health-diary",
    icon: "BookHeart" as IconName,
    category: "Patient-Facing Tools",
  },
  {
    name: "Medical History Form",
    description: "A simple form to record and print patient medical history.",
    href: "/tools/medical-history-form",
    icon: "ClipboardPlus" as IconName,
    category: "Patient-Facing Tools",
  },
  {
    name: "What’s in My Report?",
    description: "Upload any lab report PDF, AI explains it in simple language.",
    href: "/tools/report-explainer",
    icon: "FileText" as IconName,
    category: "Patient-Facing Tools",
  },
  {
    name: "Scan My Meds",
    description: "Patients scan their prescriptions and get drug guides, schedules, and interaction alerts.",
    href: "/tools/scan-meds",
    icon: "ScanLine" as IconName,
    category: "Patient-Facing Tools",
  },
  {
    name: "My Health in 1 Page",
    description: "Summarize patient’s history, conditions, meds, allergies, surgeries in 1 neat PDF.",
    href: "/tools/medical-history-form",
    icon: "FileSpreadsheet" as IconName,
    category: "Patient-Facing Tools",
  },
  {
    name: "Your Condition Visualized",
    description: "AI converts any diagnosis into an infographic-style visual explanation.",
    href: "/tools/visual-diagnosis",
    icon: "BarChartHorizontal" as IconName,
    category: "Patient-Facing Tools",
  },
];
